# -------------------
# General Run details
# -------------------
#platformToRun: "android|ios"
platformToRun: "ios"
#executionType: "local|saucelabs|awsdevicefarm|firebaseteststudio"
executionType: "local"
# testSource: "json|jama"
testSource: "json"

# -------------------
# aws devicefarm config (in case of executionType == awsdevicefarm)
# -------------------
assemblyZipFile: "src/main/assembly/devicefarm_zip.xml"


# -------------------
# Saucelabs config (in case of executionType == saucelabs)
# -------------------
sauceApikey: ""
sauceSecret: ""
sauceURL: ""
saucePort: ""


# -------------------
# Test data details
# -------------------
environment: "dev"


# -------------------
# Test Report details
# -------------------
reportMarkupTitle: "DEFAULT"
projectRepositoryUrl: "https://github.com/cvaldezscse/autonomode-mobile"
htmlReportFileName: "TEST_REPORT"
androidAppVersion: "1.4.0"
androidAppBuild: "901"
iosAppVersion: "1.4.0"
iosAppBuild: "12"


# -------------------
# Local Android
# -------------------
androidDeviceName: "Pixel 3a"
androidPlatformVersion: "12"
androidAppFileName: "AppFileName.apk"


# -------------------
# Local iOS
# -------------------
iosDeviceName: "MyiPhone"
iosPlatformVersion: "17.4.1"
iosDeviceUID: "00008110-000914283A7B801E"
iosAppFileName: "AppFileName.ipa"
iosBundleId: "com.irhythmtech.irhythm-USQA1"
defaultFontSetting: "UICTContentSizeCategoryAccessibilityL"
xcodeOrgId: "55CL7NXWST"
xcodeSigningId: "Apple Development"



# -------------------
# Appium configs
# -------------------
