<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>${markupTitle}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        table {{
            word-break: break-word;
        }}
        .status-pass {{ color: green; font-weight: bold; }}
        .status-fail {{ color: red; font-weight: bold; }}
    </style>
</head>
<body class="bg-light text-dark">
    <div class="container py-4">
        <!-- Header -->
        <div class="text-center mb-4">
            <img src="irhythm.png" alt="iRhythm" class="img-fluid mb-3" style="max-height: 100px;">
            <h2>ZioSuite Mobile App Test Report</h2>
            <h5 class="text-muted">Automation Summary</h5>
            <p><a href="${repoUrl}" class="btn btn-outline-primary btn-sm">View Repository</a></p>
            <p class="text-muted">${testplan.date}</p>
        </div>

        <!-- Summary Table -->
        <div class="card mb-4">
            <div class="card-header bg-primary text-white">
                Execution Summary
            </div>
            <div class="card-body p-0">
                <table class="table table-striped table-bordered text-center align-middle mb-0">
                    <thead class="table-light">
                        <tr>
                            <th>Platform</th>
                            <th>Environment</th>
                            <th>App Version</th>
                            <th>Time Elapsed</th>
                            <th>Completed</th>
                            <th>Pass Rate</th>
                            <th>Fail Rate</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>${platform}</td>
                            <td>${environment}</td>
                            <td>${appVersion}</td>
                            <td>${elapsedTime}</td>
                            <td>${completedCount}</td>
                            <td>${passRate}%</td>
                            <td>${failRate}%</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Test Results Table -->
        <div class="card mb-4">
            <div class="card-header bg-secondary text-white">
                Detailed Test Results
            </div>
            <div class="card-body p-0">
                <table class="table table-hover table-bordered align-middle text-center mb-0">
                    <thead class="table-light">
                        <tr>
                            <th>#</th>
                            <th>Test Case</th>
                            <th>Steps</th>
                            <th>Status</th>
                            <th>Duration</th>
                            <th>Notes</th>
                        </tr>
                    </thead>
                    <tbody>
                        <#list testcases as test>
                            <tr>
                                <td>${test_index + 1}</td>
                                <td>${test.name}</td>
                                <td>${test.steps?size}</td>
                                <td>
                                    <span class="${(test.status == 'PASS')?string('status-pass','status-fail')}">
                                        ${test.status}
                                    </span>
                                </td>
                                <td>${test.duration}</td>
                                <td>${test.notes!''}</td>
                            </tr>
                        </#list>
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Footer -->
        <footer class="text-center mt-5 mb-3">
            <p class="text-muted">Generated by ZioSuite Automation Framework</p>
        </footer>
    </div>
</body>
</html>
